Refactor/gateway
dongjangoon/Playground pull request #6
Opened 2024-12-20 05:05 UTC by lms990108

2024-12-20 05:45 UTC, dongjangoon requested changes
수고하셨습니다!

근데 AI가 코드 짜주는 거 바로 쓰지 말고 구글링해서 레퍼런스 찾아보면서 하자. 커스텀 에러나 `@AllArgsConstructor` 같은 거 검색하면 바로 나와

2024-12-20 05:45 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/config/GatewayConfig.java
> +@AllArgsConstructor
`@RequiredArgsConstructor` 를 사용하는 게 더 좋을듯?

https://www.inflearn.com/community/questions/1179578/%ED%98%B9%EC%8B%9C-allargsconstructor-%EB%A5%BC-%EC%A7%80%EC%96%91%ED%95%98%EC%8B%9C%EB%8A%94-%EC%9D%B4%EC%9C%A0%EA%B0%80-%EB%B9%8C%EB%8D%94-%ED%8C%A8%ED%84%B4%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%A8%EC%9D%B8%EA%B0%80%EC%9A%94?srsltid=AfmBOoooeD-gJglj1gi2zKsSUaxYS_FQhKssFmE4V1qBZ-O82-uR_mZj

2024-12-20 05:45 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/error/ErrorType.java
> +    UNDEFINED_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 0x5004L, "정의되지 않은 오류가 발생하였습니다.");
이거 커스텀 에러를 왜 만드는지 잘 생각해보면 더 좋을 거 같아.

도메인마다 발생할 수 있는 에러가 다른 애플리케이션과 달라서 그것들을 더 확실하게 명시해서 어떤 에러인지를 한번에 파악할 수 있는 점이 좋은 거 같은데 (디버깅, 계층 구조도)

위에 있는 `//CLIENT` 라는 부분에 있는 에러들은 그냥 기본 에러 상태니까, 저건 그냥 에러 코드로 표현할 수 있어.

그래서 여기서는 CLIENT 부분은 다 지우고, 서버 에러도 500은 어쨌든 다 서버 내부 에러고 바로 어떤 게 문제인지 파악이 안되니까 `INTERNAL_SERVER_ERROR` 만 놔두고 다 지우는 게 좋을 듯?

내가 만들어놓은 에러 한번 참고 해봐

2024-12-20 05:45 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/error/ErrorResponse.java
> +    }
여기는 생성자 오버로딩 있어서 그냥 기본 생성자 따로 적어주는 게 좋을듯

2024-12-20 05:45 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/error/ErrorType.java
> +@AllArgsConstructor
여기도 Required로

2024-12-20 05:45 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/error/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler implements org.springframework.boot.web.reactive.error.ErrorWebExceptionHandler {
이거도 수정 좀

2024-12-23 01:33 UTC, lms990108 commented on gateway/src/main/java/msa/gateway/common/error/ErrorType.java
> +    UNDEFINED_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 0x5004L, "정의되지 않은 오류가 발생하였습니다.");
근데 client 저것들이 기본에러인건 맞는데 NOT_FOUND 같은경우에 어떤걸 못찾았는지 세분화해서 확장할 생각하면 저렇게라도 만들어두는게 낫지 않아? 그래서 둔거긴한데

2024-12-23 04:00 UTC, dongjangoon commented on gateway/src/main/java/msa/gateway/common/error/ErrorType.java
> +    UNDEFINED_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 0x5004L, "정의되지 않은 오류가 발생하였습니다.");
내 에러 코드 한번 봐봐

보통 기본 에러는 에러 코드로 충분히 표현 되잖아

2024-12-23 13:25 UTC, lms990108 commented on gateway/src/main/java/msa/gateway/common/error/ErrorType.java
> +    UNDEFINED_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, 0x5004L, "정의되지 않은 오류가 발생하였습니다.");
아 이해했어 내가 적어놓은 것들은 도메인이 없는 쌩 HttpStatus랑 완전히 1:1매핑되는건데 굳이 써둔거네 그래서 클라이언트쪽이 형이 필요없다한거고

2024-12-24 07:39 UTC, merged